### ISSUE TITLE
Add support for a valid nullable boolean field type

### ISSUE THREAD

**Issue by gavbaa** [bluele/gforms#6]
Especially when doing JSON, having a boolean type field that you want to support a "Required" validation check on is not possible with the current BooleanFIeld.

**Comment by gavbaa** [comment]
I can see that as a valid use case, and so I did not try to overload that field with nullable functionality. Instead, I've created a separate NullBooleanField that can be safely nil, and passes Required validation tests. Tests included.

**Comment by bluele** [comment]
merged #5
